package app.routes.oauth2

import app.Env
import app.etc.SecureToken
import app.etc.write
import app.models.audit.GrantAuditTable
import app.models.client.Client
import app.models.client.ClientsTable
import app.models.oauth2.MachineAccessTokens
import app.models.oauth2.MachineAccessTokensTable
import app.models.oauth2.OAuth2Authorized
import app.models.oauth2.SessionAccessTokens
import app.models.oauth2.SessionAccessTokensTable
import app.routes.writeApiAudit
import io.javalin.community.routing.annotations.Get
import io.javalin.http.BadRequestResponse
import io.javalin.http.Context
import io.javalin.http.UnauthorizedResponse
import org.jetbrains.exposed.sql.transactions.transaction
import java.time.Instant
import java.time.temporal.ChronoUnit
import java.util.*

object OAuth2TokenRoute {
    @Suppress("unused")
    @Get("/api/v1/oauth2/token")
    fun token(ctx: Context) {
        val grantType = ctx.queryParam("grant_type")
            ?: throw BadRequestResponse("Missing grant_type")

        when (grantType) {
            "authorization_code" -> authorizationCode(ctx)
            "refresh_token" -> refreshToken(ctx)
            "client_credentials" -> clientCredentials(ctx)
            else -> throw BadRequestResponse("Unsupported grant_type: $grantType")
        }
    }

    private fun authorizationCode(ctx: Context) {
        val code = ctx.queryParam("code")
            ?: throw BadRequestResponse("Missing code")

        val redirectUri = ctx.queryParam("redirect_uri")
            ?: throw BadRequestResponse("Missing redirect_uri")

        val client = transaction {
            val clientId = ctx.queryParam("client_id")
                ?: throw BadRequestResponse("Missing client_id")

            val client = Client.find { ClientsTable.id eq UUID.fromString(clientId) }.firstOrNull()
                ?: throw BadRequestResponse("Invalid client_id")

            if (client.confidential) {
                val authorization = ctx.header("Authorization")
                    ?: throw BadRequestResponse("Missing Authorization header")

                if (!authorization.startsWith("Bearer "))
                    throw BadRequestResponse("Invalid Authorization header format")

                val clientCredentialsToken = authorization.substringAfter("Bearer ").trim()

                val machineAccessTokens = MachineAccessTokens.find {
                    MachineAccessTokensTable.accessToken eq clientCredentialsToken
                }.firstOrNull() ?: throw UnauthorizedResponse()

                if (!machineAccessTokens.isAccessTokenActive())
                    throw UnauthorizedResponse()
            }

            return@transaction client
        }

        transaction {
            GrantAuditTable.write(ctx, "FLOW Authorization code grant type requested.")

            val sessionAccessToken =
                SessionAccessTokens.find { SessionAccessTokensTable.authorizationCode eq code }.firstOrNull() ?: run {
                    GrantAuditTable.write(ctx, "TERM Invalid authorization code provided.")
                    throw BadRequestResponse("Invalid authorization code")
                }

            if (sessionAccessToken.client != client) {
                GrantAuditTable.write(ctx, "TERM Requested by client (${client.id.value}) but generated by client (${sessionAccessToken.client.id.value}).")
                throw BadRequestResponse("Invalid client ID")
            }

            if (!sessionAccessToken.isAuthorizationCodeActive()) {
                GrantAuditTable.write(ctx, "TERM Authorization code expired.")
                throw BadRequestResponse("Authorization code expired")
            }

            if (sessionAccessToken.redirectUri.uri != redirectUri) {
                GrantAuditTable.write(ctx, "TERM Invalid redirect_uri provided.")
                throw BadRequestResponse("Invalid redirect_uri")
            }

            GrantAuditTable.write(ctx, "FLOW Authorization code validated successfully.")

            sessionAccessToken.authorizationCode = null
            sessionAccessToken.authorizationCodeExpiration = null
            sessionAccessToken.lastRefreshed = Instant.now()

            ctx.json(
                mapOf(
                    "token_type" to "Bearer",
                    "access_token" to sessionAccessToken.accessToken,
                    "refresh_token" to sessionAccessToken.refreshToken,
                    "expires_in" to (sessionAccessToken.session.expiresAt.epochSecond - Instant.now().epochSecond)
                        .coerceAtMost(Env.SESSION_ACCESS_TOKEN_LIFETIME),
                    "refresh_token_expires_in" to sessionAccessToken.session.expiresAt.epochSecond - Instant.now().epochSecond,
                )
            )

            GrantAuditTable.write(ctx, "TERM Access token and refresh token issued.")
        }
    }

    private fun refreshToken(ctx: Context) {
        val refreshToken = ctx.queryParam("refresh_token")
            ?: throw BadRequestResponse("Missing refresh_token")

        transaction {
            GrantAuditTable.write(ctx, "FLOW Refresh token grant type requested.")

            val sessionAccessToken =
                SessionAccessTokens.find { SessionAccessTokensTable.refreshToken eq refreshToken }.firstOrNull()
                    ?: run {
                        GrantAuditTable.write(ctx, "TERM Invalid refresh token provided.")
                        throw BadRequestResponse("Invalid refresh token")
                    }

            GrantAuditTable.write(
                ctx,
                "FLOW Refresh token found for session access token (${sessionAccessToken.id.value})."
            )

            if (!sessionAccessToken.isRefreshTokenActive()) {
                GrantAuditTable.write(
                    ctx,
                    "TERM Refresh token expired for session access token (${sessionAccessToken.id.value})."
                )
                throw BadRequestResponse("Refresh token expired")
            }

            val newAccessToken = SecureToken()
            val newRefreshToken = SecureToken()

            sessionAccessToken.lastRefreshed = Instant.now()

            sessionAccessToken.accessToken = newAccessToken
            sessionAccessToken.refreshToken = newRefreshToken

            GrantAuditTable.write(
                ctx,
                "FLOW Refresh token successfully refreshed for session access token (${sessionAccessToken.id.value})."
            )

            ctx.json(
                mapOf(
                    "token_type" to "Bearer",
                    "access_token" to newAccessToken,
                    "refresh_token" to newRefreshToken,
                    "expires_in" to (sessionAccessToken.session.expiresAt.epochSecond - Instant.now().epochSecond)
                        .coerceAtMost(Env.SESSION_ACCESS_TOKEN_LIFETIME),
                    "refresh_token_expires_in" to sessionAccessToken.session.expiresAt.epochSecond - Instant.now().epochSecond
                )
            )

            ctx.writeApiAudit("Access token refreshed.")
            GrantAuditTable.write(
                ctx,
                "TERM Refresh token response sent for session access token (${sessionAccessToken.id.value})."
            )
        }
    }

    private fun clientCredentials(ctx: Context) {
        val header = ctx.header("Authorization")
            ?: throw BadRequestResponse("Missing Authorization header")

        if (!header.startsWith("Basic "))
            throw BadRequestResponse("Invalid Authorization header format")

        val base64Credentials = header.substringAfter("Basic ").trim()
        val decodedCredentials = String(Base64.getDecoder().decode(base64Credentials))
        val (clientId, clientSecret) = decodedCredentials.split(":", limit = 2)
            .takeIf { it.size == 2 }
            ?: throw BadRequestResponse("Invalid client credentials format")

        if (runCatching { UUID.fromString(clientId) }.isFailure)
            throw BadRequestResponse("Invalid client credentials format")

        val requestedScope = ctx.queryParam("scope")

        transaction {
            GrantAuditTable.write(ctx, "FLOW Client credentials grant type requested by client ($clientId).")

            val client = Client.find { ClientsTable.id eq UUID.fromString(clientId) }.firstOrNull() ?: run {
                GrantAuditTable.write(ctx, "TERM Invalid client ID provided.")
                throw BadRequestResponse("Invalid client ID")
            }

            GrantAuditTable.write(ctx, "FLOW Client (${client.id.value}) found.")

            if (client.secret != clientSecret) {
                GrantAuditTable.write(ctx, "TERM Invalid client secret provided for client (${client.id.value}).")
                throw BadRequestResponse("Invalid client secret")
            }

            GrantAuditTable.write(ctx, "FLOW Client (${client.id.value}) secret verified.")

            val accessToken = SecureToken()

            val scope = if (client.scope == null) requestedScope else {
                val clientScopes = client.scope!!.split(" ")
                val requestedScopes = requestedScope?.split(" ") ?: clientScopes

                val validScopes = requestedScopes.filter { it in clientScopes }
                if (validScopes.isNotEmpty()) validScopes.joinToString(" ") else null
            }

            GrantAuditTable.write(ctx, "FLOW Client (${client.id.value}) scopes determined: ${scope}.")

            MachineAccessTokens.new {
                this.client = client
                this.issuedAt = Instant.now()
                this.expiresAt = Instant.now().plus(1, ChronoUnit.DAYS)
                this.accessToken = accessToken
                this.scope = scope
            }

            ctx.json(
                mapOf(
                    "token_type" to "Bearer",
                    "access_token" to accessToken,
                    "expires_in" to 86400,
                    "scope" to scope
                )
            )

            GrantAuditTable.write(ctx, "TERM Generated machine access token for client (${client.id.value}).")
        }
    }

    fun Context.requireAuthorization(): OAuth2Authorized {
        if (attribute<OAuth2Authorized>("oauth2_authorization") != null)
            return attribute("oauth2_authorization")!!

        val token = this.header("Authorization")
            ?: throw UnauthorizedResponse("Missing Authorization header")

        val accessToken = token.substringAfter("Bearer ").takeIf { it.isNotBlank() }
            ?: throw UnauthorizedResponse("Invalid Authorization header format")

        return transaction {
            val sessionAccessTokens = SessionAccessTokens.find { SessionAccessTokensTable.accessToken eq accessToken }.firstOrNull()
            val machineAccessTokens = MachineAccessTokens.find { MachineAccessTokensTable.accessToken eq accessToken }.firstOrNull()

            val tokens = sessionAccessTokens ?: machineAccessTokens
            ?: throw UnauthorizedResponse("Invalid access token")

            if (!tokens.isAccessTokenActive())
                throw UnauthorizedResponse("Access token has expired")

            attribute("oauth2_authorization", tokens)

            return@transaction tokens
        }
    }
}