package com.jasminesoftwaresolutions.id.domain.services.authentication

sealed class AuthenticationFlowStepResult

object ContinueAuthenticationFlowStepResult : AuthenticationFlowStepResult()
object RetryAuthenticationFlowStepResult : AuthenticationFlowStepResult()

object BypassAuthenticationFlowStepResult : AuthenticationFlowStepResult()
